# This workflow creates a zip archive and uploads to releases

name: Create & Upload Release

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
    tags:
      - '*'
  pull_request:
    branches: [ "main" ]
    tags:
      - '*'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@master
      # Create Zip Archive
      - name: Zip Release
        uses: TheDoctor0/zip-release@0.7.6
        with:
          type: 'zip'
          filename: 'release.zip'
          exclusions: '*.git* /*.github/*'
      - name: Create Release Ttarball File
        run: |
          touch release.tar.gz
      # Create Tarball
      - name: Tarball Release
        uses: TheDoctor0/zip-release@0.7.6
        with:
          type: 'tar'
          filename: 'release.tar.gz'
          exclusions: '.git .github release.zip release.tar.gz'
      # Upload the Zip Archive to releases
      - name: Upload Release
        uses: ncipollo/release-action@v1.14.0
        with:
          artifacts: "release.zip,release.tar.gz"
          allowUpdates: true
          token: ${{ secrets.GITHUB_TOKEN }}
